Repository PH-DC/edu-helper, pull requests merged in 2021-05, with the labels that each got.

#10 About page completed
  about.html
  images/pillai-bg.png
  index.html
  style.css
Labels: enhancement

#11 Added Our Team Page and Minor Improvements here and there
  README.md
  about.html
  images/quote.png
  js/swiper.js
  style.css
  team.html
Labels: enhancement

#12 Minor Improvements
  about.html
  blog.html
  faqs.html
  images/faculty/hod_civil.jpg
  images/faculty/hod_mech.jpg
  images/faculty/principal.jpg
  images/faculty/user.png
  index.html
  style.css
  team.html
  testimonial.html
Labels: enhancement

#13 Restructured Project Structure
  .gitignore
  about.html
  assets/css/style.css
  assets/images/faculty/hod_civil.jpg
  assets/images/faculty/hod_mech.jpg
  assets/images/faculty/principal.jpg
  assets/images/faculty/user.png
  assets/images/helpers/quote.png
  assets/images/infrastructure/pillai-bg.png
  assets/images/logo.svg
  assets/js/swiper.js
  blog-posts/one.html
  blog.html
  faqs.html
  index.html
  team.html
  testimonial.html
Labels: enhancement

#14 Fix linking issue
  about.html
Labels: bug

#17 Updated Resources Page
  assets/css/resources.css
  assets/css/style.css
  assets/images/infrastructure/campus.jpeg
  assets/images/infrastructure/pillai-bg.png
  home.html
Labels: enhancement

#19 Added Resources Page
  about.html
  assets/css/resources.css
  assets/css/style.css
  assets/images/infrastructure/campus.jpeg
  blog-posts/one.html
  home.html
  index.html
  team.html
Labels: enhancement, good first issue

#22 Improved transitions and solved some bugs
  assets/css/style.css
  faqs.html
Labels: enhancement

#27 Fix Logo Issue, Improved Cards on Index.html
  .htaccess
  about.html
  assets/css/resources.css
  assets/css/style.css
  assets/images/helpers/user.png
  home.html
  index.html
Labels: bug-fix, feature-improvement

#28 .htaccess ready
  about.html
  faqs.html
  home.html
  index.html
  team.html
Labels: enhancement

#31 Coming soon page
  assets/css/style.css
  assets/images/commingsoon/cloud.png
  coming-soon.html
  index.html
Labels: addition, enhancement
